http_port: 8080

database:
  host: localhost
  port: 5432
  username: user
  password: pass
  name: nutrition
  ssl_mode: disable

redis:
  addr: localhost:6379
  password: ""
  db: 0

kafka:
  brokers:
    - localhost:9092
  topics:
    user_events: "user.events"
    meal_consumed: "meal.consumed"

user_service:
  min_name_len: 1
  max_name_len: 100
  min_weight: 30
  max_weight: 200

meal_service:
  min_name_len: 1
  max_name_len: 255
  max_weight_grams: 5000
  off_user_agent: "PP_NutritionApp/1.0 (your@email.com)"