services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-net

  postgres-users:
    image: postgres:15-alpine
    container_name: postgres-users
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    networks:
      - app-net

  postgres-meals:
    image: postgres:15-alpine
    container_name: postgres-meals
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: meals_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_meals_data:/var/lib/postgresql/data
    networks:
      - app-net

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      - CLUSTER_ID=5L6g3nShT-eMCtK--X86sw
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT_HOST://:9092,PLAINTEXT_DOCKER://:9094,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9092,PLAINTEXT_DOCKER://kafka:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_DOCKER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs   
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - app-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9094
    depends_on:
      - kafka
    networks:
      - app-net

  users-service:
    build: ./user_service
    container_name: users-service
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/config.yaml
    volumes:
    - ./user_service/config.yaml:/app/config.yaml
    depends_on:
      - postgres-users
      - redis
      - kafka
    networks:
      - app-net

  meals-service:
    build: ./meal_service
    container_name: meals-service
    ports:
      - "8081:8080"
    environment:
      - CONFIG_PATH=/app/config.yaml
    volumes:
    - ./meal_service/config.yaml:/app/config.yaml
    depends_on:
      - postgres-meals
      - redis
      - kafka
    networks:
      - app-net

volumes:
  redis_data:
  postgres_users_data:
  postgres_meals_data:
  kafka_data:

networks:
  app-net:
    name: app-net
    driver: bridge