http_port: 8080

database:
  host: postgres-users
  port: 5432
  username: user
  password: pass
  name: users_db
  ssl_mode: disable

kafka:
  brokers:
    - kafka:9094
  meal_consumed_topic_name: "meal.consumed"

user_service:
  min_name_len: 1
  max_name_len: 100
  min_weight: 30
  max_weight: 200