http_port: 8081

database:
  host: postgres-meals
  port: 5432
  username: user
  password: pass
  name: meals_db
  ssl_mode: disable

redis:
  addr: redis:6379
  password: ""
  db: 0

kafka:
  brokers:
    - kafka:9094
  meal_consumed_topic_name: "meal.consumed"

meal_service:
  min_name_len: 1
  max_name_len: 255
  max_weight_grams: 5000
  off_user_agent: "StudyProject/1.0 (efartem04@gmail.com)"